# Generated by Django 2.2.17 on 2020-11-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20201125_1142'),
        ('book', '0003_auto_20201125_1328'),
    ]

    operations = [
    ]
