# Generated by Django 2.2.17 on 2020-11-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_merge_20201127_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
